---
title: Planeringsverktyg Decidim
---

graph LR
    %% Sektion 1: Typ av process
    S1[**1 Typ av process**]
    S1 --> S1Q1{Har processen tidsbestämda steg?}
    S1Q1 -->|Ja| S1A1[Skapa en Process. Ställ in steg, typiskt sett efter vad som ska gå att göra för deltagare i processen. Till exempel tidsbestämda steg för förslagsinlämning, omröstning, utvärdering, genomförande.]
    S1Q1 -->|Nej| S1A2[]
    S1A2 --> S1Q2{Ska processen användas specifikt för medborgarförslag eller namninsamlingar?}
    S1Q2 -->|Ja| S1A3[Skapa ett Initiativ. Ställ in minsta antal röster per förslag. Förslagslämnare kan skapa en informationssida om sitt förslag.]
    S1Q2 -->|Nej| S1A4[Skapa ett Samråd. Ställ in samrådet som tidsbegränsat med slutdatum, eller som löpande utan slutdatum. Lägg eventuellt till presentationer av officiella deltagare.]

    %% Sektion 2: Deltagare
    S2[**2 Deltagare**]
    S2 --> S2Q1{Vilka ska kunna delta?}
    S2Q1 -->|Alla| S2A1[]
    S2Q1 -->|Inbjudna| S2A2[Ställ in som Privat. Lägg till deltagare en och en eller importera en csv-fil med namn och e-postadresser.]
    S2Q1 -->|Deltagare som uppfyller vissa kriterier| S2A3[Aktivera verifiering av deltagare.]
    S2A3 --> S2Q2{Hur ska deltagarna verifieras?}
    S2Q2 -.->|Genom att ladda upp ett identitetsdokument, som godkänns av en administratör på plattformen.| S2A4[En systemadministratör aktiverar auktoriseringen Identitetsdokument. Ställ in för varje komponent när verifieringen ska användas, till exempel för att lämna förslag eller rösta.]
    S2Q2 -.->|Med en kod, som kan skickas ut med brev.| S2A5[En systemadministratör aktiverar auktoriseringen Kod via fysiskt brev. Ställ in för varje komponent när verifieringen ska användas, till exempel för att lämna förslag eller rösta.]
    S2Q2 -.->|Mot ett medlemsregister.| S2A6[En systemadministratör aktiverar auktoriseringen Organisationens medlemslista. Ladda upp medlemslista som csv-fil under Deltagare > Auktoriseringar > Organisationens medlemslista. Ställ in för varje komponent när verifieringen ska användas, till exempel för att lämna förslag eller rösta.]
    S2Q2 -.->|På ett annat sätt.| S2A7[Det går att utveckla egna plugins för verifiering av deltagare.]
    S2A2 --> S2Q3{Vilka ska kunna se processen?}
    S2Q3 -->|Alla| S2A8[Ställ in som Transparent.]
    S2Q3 -->|Inbjudna| S2A9[]

    %% Sektion 3: Förslag
    S3[**3 Förslag**]
    S3 --> S3Q1{Ska förslag leda till beslut?}
    S3Q1 -->|Nej, bara diskussion| S3A1[Lägg till komponenten Debatt för att kunna sammanfatta diskussioner. Eller använd förslagskomponenten med kommentarer aktiverade.]
    S3Q1 -->|Ja| S3A2[Lägg till komponenten Förslag]
    S3A2 --> S3Q2{Hur skapas förslag?}
    S3A2 --> S3Q3{Är förslagen knutna till geografiska platser?}
    S3Q3 -->|Ja| S3A3[Aktivera Visning på karta]
    S3A3 -->S3Q3B{Ska förslagslämnarna kunna använda sin aktuella plats automatiskt?}
    S3Q3B --> |Ja| S3A3B[Installera pluginen Reporting Proposals, som kan användas för att till exempel rapportera om trasiga gatlyktor. Den gör det även möjligt att ta en bild och lägga till, och kontrollera om andra förslag lagts i närheten.]
    S3Q2 -.->|Deltagare skapar egna förslag| S3A4[Aktivera Deltagare skapar förslag under aktuellt steg i processen]
    S3Q2 -.->|Administratör lägger till förslag| S3A5[Aktivera officiella förslag]
    S3Q2 -.->|Deltagare diskuterar fram en längre text mening för mening| S3A6[Aktivera kollaborativa texter]
    S3Q2 -.->|Deltagare skapar utkast till förslag som andra deltagare kan begära tillgång till för att göra justeringar| S3A7[Aktivera gemensamma utkast]
    S3Q2 -.->|Deltagare kan göra ändringsförslag till andras förslag, men de måste godkännas av förslagsförfattaren| S3A8[Aktivera ändringsförslag]
    S3Q2 -.->|Förslagen tas fram på möten| S3A9[Koppla förslagen till möten i möteskomponenten]

    %% Sektion 4: Beslut
    S4[**4 Beslut**]
    S4 --> S4Q1{Hur fattas beslut?}
    S4Q1 --> |Deltagare röstar. Förslag som fått röster upp till en viss gräns går vidare| S4A1[Aktivera Röster under aktuellt steg för Förslag. Ställ in Minst antal stöd per förslag som gräns och Antal röster per deltagare]
    S4Q1 --> |Deltagare röstar utifrån en bestämd budget där varje förslag får en viss kostnad| S4A2[Lägg till komponenten Budget. När Förslagsinlämningen är klar importerar du förslag från Förslagskomponenten till Budgetkomponenten.]
    S4A2 --> S4Q2{Hur väljer deltagarna förslag?}
    S4Q2 --> |Ett visst antal förslag| S4A3[Ställ in Budgetkomponenten, antingen Minsta antal projekt att rösta på, eller Minsta och högsta antal projekt att rösta på]
    S4Q2 --> |Upp till en viss summa| S4A4[Ställ in Budgetkomponenten, Aktivera regel Lägsta procentandel av budget]
    S4Q1 --> |Processen är rådgivande men det ska synas vilka förslag som är populärast| S4A5[Aktivera gilla-markeringar för aktuellt steg. Eller aktivera Röster under aktuellt steg och sätt Minst antal stöd per förslag till 0 för att inte ha någon specifik gräns för antal röster]

    %% Sektion 5: Möten
    S5[**5 Möten**]
    S5 --> S5Q1{Har processen några event eller möten?}
    S5Q1 -->|Ja|S5A1[Lägg till komponenten Möten]
    S5A1 --> S5Q2{Är mötena fysiska eller digitala eller olika för olika möten?}
    S5Q2 -.-> |Fysiska| S5A2[Lägg till möte och ställ in Fysiskt. Lägg till adress och vägbeskrivning.]
    S5Q2 -.-> |Digitala| S5A3[Lägg till möte och ställ in Digitalt. Lägg till länk till videomöte.]
    S5Q2 -.-> |Hybridmöten| S5A4[Lägg till möte och ställ in Hybridmöte. Lägg till adress och vägbeskrivning. Lägg till länk till videomöte.]
    S5A1 --> S5Q3{Behöver deltagare anmäla sig?}
    S5Q3 --> |Ja| S5A5[I mötets inställningar, välj På den här plattformen under Typ av registrering. I översikten över möten, klicka ikonen för Registreringar och ställ in antal platser och villkor för registrering.]
    S5A1 --> S5Q4{Finns det en dagordning?}
    S5Q4 --> |Ja| S5A6[I översikten över möten, klicka ikonen för Dagordning och lägg till tid och beskrivning för olika punkter.]

    %% Sektion 6: Uppföljning
    S6[**6 Uppföljning**]
    S6 --> S6Q1{Hur följs besluten eller förslagen upp?}
    S6Q1 -.->|Utvärderingsformulär till deltagare|S6A1[Lägg till komponenten Enkät och ställ in utvärderingsfrågor.]
    S6Q1 -.->|Utskick till deltagare|S6A2[Använd Nyhetsbrevsfunktionen för att göra utskick till de som deltagit i eller följer processen.]
    S6Q1 -.->|Vinnande förslag visas på plattformen|S6A3[Om Budget-komponenten används, markera vinnande förslag som Valt för genomförande. Om bara Förslags-komponenten används, besvara förslag som Accepterade.]
    S6Q1 -.->|Genomförandet av förslag dokumenteras på plattformen|S6A4[Lägg till komponenten Genomförande. Ställ in status för genomförande. Importera förslag från Budget- eller Förslags-komponentent. Lägg in uppdateringar av hur genomförandet går.]
