name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Möjliggör manuell körning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install ejs

      - name: Create asset directories
        run: mkdir -p public/assets/js

      - name: Generate HTML
        run: node generator/index.js

      - name: Copy JS files to public directory
        run: |
          # Kopierar JavaScript-filerna till public-mappen om de inte redan finns där
          cp -r assets/js/* public/assets/js/ || echo "No assets/js directory found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
